# Generated by Django 2.2.3 on 2019-09-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wish',
            new_name='Item',
        ),
    ]
